[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cofolder"
version = "0.0.0-dev"
description = "Collection of helpful tools for performing various co-folding tasks using cofolding models (e.g. Boltz.)"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
  {name = "Remco L. van den Broek", email = "r.l.van.den.broek@lacdr.leidenuniv.nl"},
  {name = "Bola Khalil", email = "b.a.a.khalil@lacdr.leidenuniv.nl"}
]
requires-python = ">=3.11"
dependencies = [
    "rdkit",
    "matplotlib",
    "seaborn",
    "gemmi",
    "prolif",
    "pdb2pqr",
]

[project.optional-dependencies]
boltz1 = [
    "boltz==1.0.0; python_version < '3.13'",
]
boltz2 = [
    "boltz[cuda]; python_version < '3.13'",
]
boltz-community = [
    "boltz-community[cuda] @ git+https://github.com/Novel-Therapeutics/boltz-community.git",
]
acceptance = [
    "marimo>=0.23,<0.24",
]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
]
docs = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.5.0",
    "mkdocstrings[python]>=0.24.0",
    "mkdocs-autorefs>=0.5.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]
ui = [
    "streamlit>=1.28.0",
    "streamlit-option-menu>=0.3.6",
    "pyyaml"
]

[project.scripts]
cofolder = "cofolder.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["cofolder*"]

[tool.setuptools.package-data]
"cofolder.acceptance" = ["data/*.yaml", "data/*.csv"]
