"""Bias analytics with a stable compatibility facade."""

from __future__ import annotations


from ._common import (
    ALIGNER as ALIGNER,
    BIAS_LIGAND_PAIR_FILE_STEM as BIAS_LIGAND_PAIR_FILE_STEM,
    BIAS_LIGAND_VIEW_MIN_SIMILARITY as BIAS_LIGAND_VIEW_MIN_SIMILARITY,
    BIAS_PAIRING_COMPONENT_1_ONLY as BIAS_PAIRING_COMPONENT_1_ONLY,
    BIAS_PAIRING_COMPONENT_2_ONLY as BIAS_PAIRING_COMPONENT_2_ONLY,
    BIAS_PAIRING_LIGAND_ONLY as BIAS_PAIRING_LIGAND_ONLY,
    BIAS_PAIRING_PAIRED as BIAS_PAIRING_PAIRED,
    BIAS_PAIRING_PROTEIN_ONLY as BIAS_PAIRING_PROTEIN_ONLY,
    BIAS_PLOT_FILE_STEM as BIAS_PLOT_FILE_STEM,
    BIAS_PLOT_LIGAND_THRESHOLD as BIAS_PLOT_LIGAND_THRESHOLD,
    BIAS_PLOT_SEQUENCE_THRESHOLD as BIAS_PLOT_SEQUENCE_THRESHOLD,
    BIAS_PLOT_SKIPPED_FILE as BIAS_PLOT_SKIPPED_FILE,
    BIAS_PROGRESS_LOG_EVERY as BIAS_PROGRESS_LOG_EVERY,
    BIAS_PROGRESS_WRITE_EVERY as BIAS_PROGRESS_WRITE_EVERY,
    BIAS_PROTEIN_PAIR_FILE_STEM as BIAS_PROTEIN_PAIR_FILE_STEM,
    BIAS_PROTEIN_VIEW_MIN_SIMILARITY as BIAS_PROTEIN_VIEW_MIN_SIMILARITY,
    BIAS_TRAINING_DATA_COLUMNS as BIAS_TRAINING_DATA_COLUMNS,
    CORE_ENTRY_URL as CORE_ENTRY_URL,
    CORE_NONPOLY_URL as CORE_NONPOLY_URL,
    CUSTOM_LIGAND_REQUIRED_COLUMNS as CUSTOM_LIGAND_REQUIRED_COLUMNS,
    CUSTOM_PROTEIN_REQUIRED_COLUMNS as CUSTOM_PROTEIN_REQUIRED_COLUMNS,
    FASTA_URL as FASTA_URL,
    LIGAND_BASE_COLUMNS as LIGAND_BASE_COLUMNS,
    MORGAN_FP as MORGAN_FP,
    PROTEIN_BASE_COLUMNS as PROTEIN_BASE_COLUMNS,
    PROVENANCE_COLUMNS as PROVENANCE_COLUMNS,
    REFERENCE_PATH_COLUMNS as REFERENCE_PATH_COLUMNS,
    SAME_TYPE_PAIR_DATA_COLUMNS as SAME_TYPE_PAIR_DATA_COLUMNS,
    _canonical_reference_source as _canonical_reference_source,
    _empty_ligand_reference_frame as _empty_ligand_reference_frame,
    _empty_protein_reference_frame as _empty_protein_reference_frame,
    _is_before_cutoff as _is_before_cutoff,
    _norm_id as _norm_id,
    _normalize_reference_path_fields as _normalize_reference_path_fields,
    _normalize_smiles as _normalize_smiles,
    _order_ligand_training_columns as _order_ligand_training_columns,
    _order_protein_training_columns as _order_protein_training_columns,
    _parse_iso_date as _parse_iso_date,
    _path_cache_token as _path_cache_token,
)

from ._references import (
    _components_cif_smiles_index as _components_cif_smiles_index,
    _concat_reference_frames as _concat_reference_frames,
    _extract_system_queries as _extract_system_queries,
    _finalize_reference_frame as _finalize_reference_frame,
    _load_custom_ligand_training as _load_custom_ligand_training,
    _load_custom_protein_training as _load_custom_protein_training,
    _load_ligand_training as _load_ligand_training,
    _load_protein_training as _load_protein_training,
    _load_public_ligand_training as _load_public_ligand_training,
    _load_public_protein_training as _load_public_protein_training,
    _read_ligand_training_from_sdf as _read_ligand_training_from_sdf,
    _smiles_from_ccd_cache as _smiles_from_ccd_cache,
    _smiles_from_components_cif as _smiles_from_components_cif,
)

from ._similarity import (
    _best_ligand_hit as _best_ligand_hit,
    _best_pairwise_protein_hit as _best_pairwise_protein_hit,
    _best_protein_hit as _best_protein_hit,
    _best_reference_row as _best_reference_row,
    _build_ligand_training_views as _build_ligand_training_views,
    _build_protein_training_view as _build_protein_training_view,
    _ligand_similarity_series as _ligand_similarity_series,
    _morgan_fp_from_normalized_smiles as _morgan_fp_from_normalized_smiles,
    _morgan_fp_from_smiles as _morgan_fp_from_smiles,
    _pairwise_sequence_identity_percent as _pairwise_sequence_identity_percent,
    _protein_pairwise_similarity_series as _protein_pairwise_similarity_series,
    _protein_similarity_series as _protein_similarity_series,
    _reference_rows_for_query as _reference_rows_for_query,
)

from ._datasets import (
    _all_query_groups as _all_query_groups,
    _bias_training_row_from_sources as _bias_training_row_from_sources,
    _build_bias_training_dataset as _build_bias_training_dataset,
    _build_bias_training_rows as _build_bias_training_rows,
    _build_ligand_reference_index as _build_ligand_reference_index,
    _build_protein_lookup_index as _build_protein_lookup_index,
    _build_same_type_pair_rows as _build_same_type_pair_rows,
    _collapse_pair_value as _collapse_pair_value,
    _combine_prefixed_rows as _combine_prefixed_rows,
    _combined_mixed_pair_bias_training_dataframe as _combined_mixed_pair_bias_training_dataframe,
    _component_similarity_column as _component_similarity_column,
    _component_threshold as _component_threshold,
    _dedupe_query_group_view as _dedupe_query_group_view,
    _direct_overlap_reference_keys as _direct_overlap_reference_keys,
    _finalize_bias_training_dataframe as _finalize_bias_training_dataframe,
    _finalize_same_type_pair_dataframe as _finalize_same_type_pair_dataframe,
    _ligand_query_groups as _ligand_query_groups,
    _matching_reference_rows as _matching_reference_rows,
    _normalize_component_similarity as _normalize_component_similarity,
    _pairing_sort_order as _pairing_sort_order,
    _prepare_reference_side as _prepare_reference_side,
    _protein_query_groups as _protein_query_groups,
    _reference_key_from_row as _reference_key_from_row,
    _reference_label_from_component_rows as _reference_label_from_component_rows,
    _reference_label_from_merged_row as _reference_label_from_merged_row,
    _reference_ligand_similarity_rows as _reference_ligand_similarity_rows,
    _reference_pdb_id_from_bias_row as _reference_pdb_id_from_bias_row,
    _reference_pdb_id_from_same_type_row as _reference_pdb_id_from_same_type_row,
    _reference_protein_similarity_rows as _reference_protein_similarity_rows,
    _safe_pair_file_token as _safe_pair_file_token,
    _same_type_pair_row_from_sources as _same_type_pair_row_from_sources,
    _same_type_pair_sort_order as _same_type_pair_sort_order,
    _sort_bias_training_dataset as _sort_bias_training_dataset,
    _sort_same_type_pair_dataset as _sort_same_type_pair_dataset,
    _subset_group_ligand_view as _subset_group_ligand_view,
    _subset_group_protein_view as _subset_group_protein_view,
)

from ._enrichment import (
    _cached_pdb_ligand_entries as _cached_pdb_ligand_entries,
    _cached_pdb_protein_similarity_rows as _cached_pdb_protein_similarity_rows,
    _enrich_mixed_bias_dataset_with_pdb_backfill as _enrich_mixed_bias_dataset_with_pdb_backfill,
    _enrich_mixed_bias_row_with_pdb_backfill as _enrich_mixed_bias_row_with_pdb_backfill,
    _enrich_same_type_ligand_pair_dataset_with_pdb_backfill as _enrich_same_type_ligand_pair_dataset_with_pdb_backfill,
    _enrich_same_type_ligand_pair_row_with_pdb_backfill as _enrich_same_type_ligand_pair_row_with_pdb_backfill,
    _entry_fasta_sequences as _entry_fasta_sequences,
    _entry_ligand_ids as _entry_ligand_ids,
    _extract_nonpoly_comp_id as _extract_nonpoly_comp_id,
    _fetch_json as _fetch_json,
    _fetch_text as _fetch_text,
    _flatten_resolved_bias_rows as _flatten_resolved_bias_rows,
    _log_bias_lookup_progress as _log_bias_lookup_progress,
    _pdb_ligand_similarity_rows as _pdb_ligand_similarity_rows,
    _pdb_protein_similarity_rows as _pdb_protein_similarity_rows,
    _pending_bias_rows as _pending_bias_rows,
    _resolve_pdb_ligand_smiles as _resolve_pdb_ligand_smiles,
    _resolved_mmseqs_bin_token as _resolved_mmseqs_bin_token,
    _write_fasta_records as _write_fasta_records,
    _write_progress_checkpoint as _write_progress_checkpoint,
)

from ._artifacts import (
    _build_reference_landscape_row as _build_reference_landscape_row,
    _clear_pair_specific_artifacts as _clear_pair_specific_artifacts,
    _materialize_bias_training_views as _materialize_bias_training_views,
    _materialize_reference_landscape_summary as _materialize_reference_landscape_summary,
    _mixed_pair_dataset as _mixed_pair_dataset,
    _pair_specific_bias_training_datasets as _pair_specific_bias_training_datasets,
    _same_type_pair_dataset as _same_type_pair_dataset,
    _skip_plot_message as _skip_plot_message,
    _write_bias_plot_artifacts as _write_bias_plot_artifacts,
    _write_same_type_plot_artifacts as _write_same_type_plot_artifacts,
)

from ._workflow import (
    apply_bias_metrics as apply_bias_metrics,
)

_COMPATIBILITY_EXPORTS = [
    "ALIGNER",
    "BIAS_LIGAND_PAIR_FILE_STEM",
    "BIAS_LIGAND_VIEW_MIN_SIMILARITY",
    "BIAS_PAIRING_COMPONENT_1_ONLY",
    "BIAS_PAIRING_COMPONENT_2_ONLY",
    "BIAS_PAIRING_LIGAND_ONLY",
    "BIAS_PAIRING_PAIRED",
    "BIAS_PAIRING_PROTEIN_ONLY",
    "BIAS_PLOT_FILE_STEM",
    "BIAS_PLOT_LIGAND_THRESHOLD",
    "BIAS_PLOT_SEQUENCE_THRESHOLD",
    "BIAS_PLOT_SKIPPED_FILE",
    "BIAS_PROGRESS_LOG_EVERY",
    "BIAS_PROGRESS_WRITE_EVERY",
    "BIAS_PROTEIN_PAIR_FILE_STEM",
    "BIAS_PROTEIN_VIEW_MIN_SIMILARITY",
    "BIAS_TRAINING_DATA_COLUMNS",
    "CORE_ENTRY_URL",
    "CORE_NONPOLY_URL",
    "CUSTOM_LIGAND_REQUIRED_COLUMNS",
    "CUSTOM_PROTEIN_REQUIRED_COLUMNS",
    "FASTA_URL",
    "LIGAND_BASE_COLUMNS",
    "MORGAN_FP",
    "PROTEIN_BASE_COLUMNS",
    "PROVENANCE_COLUMNS",
    "REFERENCE_PATH_COLUMNS",
    "SAME_TYPE_PAIR_DATA_COLUMNS",
    "_canonical_reference_source",
    "_empty_ligand_reference_frame",
    "_empty_protein_reference_frame",
    "_is_before_cutoff",
    "_norm_id",
    "_normalize_reference_path_fields",
    "_normalize_smiles",
    "_order_ligand_training_columns",
    "_order_protein_training_columns",
    "_parse_iso_date",
    "_path_cache_token",
    "_components_cif_smiles_index",
    "_concat_reference_frames",
    "_extract_system_queries",
    "_finalize_reference_frame",
    "_load_custom_ligand_training",
    "_load_custom_protein_training",
    "_load_ligand_training",
    "_load_protein_training",
    "_load_public_ligand_training",
    "_load_public_protein_training",
    "_read_ligand_training_from_sdf",
    "_smiles_from_ccd_cache",
    "_smiles_from_components_cif",
    "_best_ligand_hit",
    "_best_pairwise_protein_hit",
    "_best_protein_hit",
    "_best_reference_row",
    "_build_ligand_training_views",
    "_build_protein_training_view",
    "_ligand_similarity_series",
    "_morgan_fp_from_normalized_smiles",
    "_morgan_fp_from_smiles",
    "_pairwise_sequence_identity_percent",
    "_protein_pairwise_similarity_series",
    "_protein_similarity_series",
    "_reference_rows_for_query",
    "_all_query_groups",
    "_bias_training_row_from_sources",
    "_build_bias_training_dataset",
    "_build_bias_training_rows",
    "_build_ligand_reference_index",
    "_build_protein_lookup_index",
    "_build_same_type_pair_rows",
    "_collapse_pair_value",
    "_combine_prefixed_rows",
    "_combined_mixed_pair_bias_training_dataframe",
    "_component_similarity_column",
    "_component_threshold",
    "_dedupe_query_group_view",
    "_direct_overlap_reference_keys",
    "_finalize_bias_training_dataframe",
    "_finalize_same_type_pair_dataframe",
    "_ligand_query_groups",
    "_matching_reference_rows",
    "_normalize_component_similarity",
    "_pairing_sort_order",
    "_prepare_reference_side",
    "_protein_query_groups",
    "_reference_key_from_row",
    "_reference_label_from_component_rows",
    "_reference_label_from_merged_row",
    "_reference_ligand_similarity_rows",
    "_reference_pdb_id_from_bias_row",
    "_reference_pdb_id_from_same_type_row",
    "_reference_protein_similarity_rows",
    "_safe_pair_file_token",
    "_same_type_pair_row_from_sources",
    "_same_type_pair_sort_order",
    "_sort_bias_training_dataset",
    "_sort_same_type_pair_dataset",
    "_subset_group_ligand_view",
    "_subset_group_protein_view",
    "_cached_pdb_ligand_entries",
    "_cached_pdb_protein_similarity_rows",
    "_enrich_mixed_bias_dataset_with_pdb_backfill",
    "_enrich_mixed_bias_row_with_pdb_backfill",
    "_enrich_same_type_ligand_pair_dataset_with_pdb_backfill",
    "_enrich_same_type_ligand_pair_row_with_pdb_backfill",
    "_entry_fasta_sequences",
    "_entry_ligand_ids",
    "_extract_nonpoly_comp_id",
    "_fetch_json",
    "_fetch_text",
    "_flatten_resolved_bias_rows",
    "_log_bias_lookup_progress",
    "_pdb_ligand_similarity_rows",
    "_pdb_protein_similarity_rows",
    "_pending_bias_rows",
    "_resolve_pdb_ligand_smiles",
    "_resolved_mmseqs_bin_token",
    "_write_fasta_records",
    "_write_progress_checkpoint",
    "_build_reference_landscape_row",
    "_clear_pair_specific_artifacts",
    "_materialize_bias_training_views",
    "_materialize_reference_landscape_summary",
    "_mixed_pair_dataset",
    "_pair_specific_bias_training_datasets",
    "_same_type_pair_dataset",
    "_skip_plot_message",
    "_write_bias_plot_artifacts",
    "_write_same_type_plot_artifacts",
    "apply_bias_metrics",
]

__all__ = [name for name in _COMPATIBILITY_EXPORTS if not name.startswith("_")]
